version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db

  redis:
      image: redis
      restart: always
      ports:
        - "6378:6378"
      volumes:
        - ./redis-data:/data